export const EVENT_TEMPLATES: Record<string, unknown> = {
  'Empty': {},
  'API Gateway HTTP API v2': {
    version: '2.0', routeKey: 'GET /hello', rawPath: '/hello',
    rawQueryString: 'name=world',
    headers: { accept: '*/*' },
    queryStringParameters: { name: 'world' },
    requestContext: { http: { method: 'GET', path: '/hello' } },
    isBase64Encoded: false,
  },
  'API Gateway proxy (v1)': {
    resource: '/{proxy+}', path: '/hello', httpMethod: 'GET',
    headers: { Accept: '*/*' }, queryStringParameters: { name: 'world' },
    pathParameters: { proxy: 'hello' }, body: null, isBase64Encoded: false,
  },
  'S3 put': { Records: [{ eventVersion: '2.1', eventSource: 'aws:s3',
    awsRegion: 'us-east-1', eventName: 'ObjectCreated:Put',
    s3: { bucket: { name: 'example-bucket', arn: 'arn:aws:s3:::example-bucket' },
      object: { key: 'test/key.txt', size: 1024 } } }] },
  'SQS message': { Records: [{ messageId: '19dd0b57-b21e-4ac1-bd88-01bbb068cb78',
    receiptHandle: 'MessageReceiptHandle', body: 'Hello from SQS!',
    attributes: { ApproximateReceiveCount: '1' }, eventSource: 'aws:sqs',
    awsRegion: 'us-east-1' }] },
  'EventBridge': { version: '0', id: 'fdd6cb98-d2e2-4ecf-a6f6-1d8b0f4e327a',
    'detail-type': 'Scheduled Event', source: 'aws.events',
    time: '2026-01-01T00:00:00Z', region: 'us-east-1', detail: {} },
  'DynamoDB stream': { Records: [{ eventID: '1', eventName: 'INSERT',
    eventSource: 'aws:dynamodb', awsRegion: 'us-east-1',
    dynamodb: { Keys: { Id: { N: '101' } },
      NewImage: { Id: { N: '101' }, Message: { S: 'hello' } },
      StreamViewType: 'NEW_AND_OLD_IMAGES' } }] },
}
