export type {
  Runtime,
  SavedEvent,
  FunctionTrigger,
  FunctionDef,
  Ports,
  ServiceCredential,
  LocalService,
  ServicesStatus,
  TriggerStatus,
  TriggersStatus,
  RuntimeHealth,
  Health,
  Detection,
  LambdaError,
  InvokeError,
  Span,
  Trace,
  CheckResult,
  Report,
  InvokeReport,
  InvokeResult,
  InvokeOutcome,
  InvokeSource,
  HistoryEntry,
  FunctionStats,
  ApiResult,
  PollerStatus,
} from '@aws-playground/shared'

export type ResultTab = 'response' | 'logs' | 'report' | 'trace' | 'checks' | 'history'
export const RESULT_TABS: ResultTab[] = ['response', 'logs', 'report', 'trace', 'checks', 'history']
